### ISSUE TITLE
View icon and title is not initalized

### ISSUE THREAD

**Issue by pke** [njbartlett/Extensions2Services#1]
setInitializationData of WorkbenchPart is not called anymore when using the bundles name.neilbartlett.extsvcs.core.InjectionFactory to create views.
I think it should be called on the returned factory object.

**Comment by pke** [comment]
I added the view config element to the  InjectedFactory.createInstance() method name.neilbartlett.extsvcs.core.internal.InjectedFactory.createInstance(IConfigurationElement) 
and  added 

if (object instanceof IExecutableExtension) {
            ((IExecutableExtension) object).setInitializationData(config, ATTR_FACTORY_CLASS, null);
        }

Now views have a title and icons again.

**Comment by njbartlett** [comment]
Fixed in latest commit
